### ISSUE TITLE
How to properly get 24 pulses for each quarter note?

### ISSUE THREAD

**Issue by DatanoiseTV** [Ableton/link#109]
I am working on a device that uses Link (on ESP32). I need to make a midi clock with 24 pulses.

If I do
```
bool lastState = false;


.....
bool currentState = fmodf(phase, 1.0 / 12) < 0.5/12;
if(lastState != currentState){
    ... send midi clock
lastState = currentState;
}
```

The FreeRTOS task is highest priorty, but my MIDI clock is jittering +/- 1 bpm and therefore
drifts away.

What is the proper way to get 24 pulses? Maybe @mathiasbredholt can help?

**Comment by mathiasbredholt** [comment]
The code above should work, is it based on the example code? I noticed that the `portYIELD()` should be removed from the tick task in the example as it will prevent the Link task to run otherwise.
```
  while (true)
  {
    xSemaphoreTake(handle, portMAX_DELAY);

    const auto state = link.captureAudioSessionState();
    const auto phase = state.phaseAtTime(link.clock().micros(), 1.);
    gpio_set_level(LED, fmodf(phase, 1.) < 0.1);
    portYIELD();
  }
```

**Comment by DatanoiseTV** [comment]
@mathiasbredholt The gpio_set_level(LED, fmodf(phase, 1.) < 0.1); works okay, but I am not sure
how to call midi_clock_send() 24 times in one phase-cycle instead of gpio_set_level()...

**Comment by mathiasbredholt** [comment]
I would probably just do something like
```
int currentState = phase * 24;
if (currentState == 0 && lastState != currentState) {
  // send midi clock
} 
```

**Comment by DatanoiseTV** [comment]
@mathiasbredholt First one doesn't get triggered somehow. I will investigate a bit more. I'd like to get it as jitter-less as possible.

**Comment by mathiasbredholt** [comment]
@DatanoiseTV did you try the second solution?

You can reach out at support at torsoelectronics.com.

**Comment by mathiasbredholt** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/8356424/146645112-c3e64061-9475-4aaa-a572-97328f81a842.png">

@DatanoiseTV  and I have been trying to generate an accurate MIDI clock from Link on ESP32, but we're experiencing issues with shootouts in the jitter of the clock. On this plot, the shootouts seems to be periodic with ~30 sec, I wonder if there's any timeouts in Link with this period @fgo-ableton?

**Comment by mathiasbredholt** [comment]
Ok possibly this one in `Sessions.hpp`?
```
  void scheduleRemeasurement()
  {
    // set a timer to re-measure the active session after a period
    mTimer.expires_from_now(std::chrono::microseconds{30000000});
    mTimer.async_wait([this](const typename Timer::ErrorCode e) {
      if (!e)
      {
        launchSessionMeasurement(mCurrent);
        scheduleRemeasurement();
      }
    });
  }
```

**Comment by DatanoiseTV** [comment]
> Ok possibly this one in `Sessions.hpp`?
> 
> ```
>   void scheduleRemeasurement()
>   {
>     // set a timer to re-measure the active session after a period
>     mTimer.expires_from_now(std::chrono::microseconds{30000000});
>     mTimer.async_wait([this](const typename Timer::ErrorCode e) {
>       if (!e)
>       {
>         launchSessionMeasurement(mCurrent);
>         scheduleRemeasurement();
>       }
>     });
>   }
> ```

I tried removing it and changing the interval. It just delays the problem or makes it appear faster.

**Comment by CarloCattano** [comment]
https://github.com/Ableton/link/pull/72#issue-564038499

**Comment by fgo-ableton** [comment]
> @DatanoiseTV and I have been trying to generate an accurate MIDI clock from Link on ESP32, but we're experiencing issues with shootouts in the jitter of the clock. On this plot, the shootouts seem to be periodic with ~30 sec, I wonder if there's any timeouts in Link with this period @fgo-ableton?

Yes. Link periodically re-measures the timing offset with other peers. As this will update the host time / beat time relation it can lead to jumps in the timeline. This would be expected behaviour. The time difference depends on the amount of clock drift between the different devices. In this case you should let the midi clock catch up smoothly with Link. (Some kind of low pass filter like behaviour).
Is the behaviour the same for the device that enabled Link first and a device that joined a session? If the issue only exists on devices that join an existing session this is likely what happens.

Another issue causing this could be that the measurement blocks the loop that generates the MIDI ticks. In this case pinning Link to a different core than the one generating MIDI could help.

**Comment by mathiasbredholt** [comment]
> Yes. Link periodically re-measures the timing offset with other peers. As this will update the host time / beat time relation it can lead to jumps in the timeline. This would be expected behaviour.

I understand, this would explain the shootouts.

> The time difference depends on the amount of clock drift between the different devices. In this case you should let the midi clock catch up smoothly with Link. (Some kind of low pass filter like behaviour).

 I had expected that the filtering of the measurements within Link would smooth out the jumps, but a filter solution would work :)

> Is the behaviour the same for the device that enabled Link first and a device that joined a session? If the issue only exists on devices that join an existing session this is likely what happens.

Haven't checked this yet, but will do!

> Another issue causing this could be that the measurement blocks the loop that generates the MIDI ticks. In this case pinning Link to a different core than the one generating MIDI could help.

I think @DatanoiseTV have tried a lot of switching around priorities and tasks/pinning to cores and it doesn't seem to resolve the issue.

**Comment by mathiasbredholt** [comment]
I came up with a filter solution that works pretty well for my tests. The idea is to generate a phase signal from the BPM and then calculate the error between the BPM and Link generated phases. The error is used to lock the BPM generated phase signal to the Link timeline with an adjustable lag. The lag can be adjusted by changing the gain of the error signal.   

I implemented it in a PD patch below:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/8356424/148589727-ac31d4bd-0c13-4779-a778-47c89b39e140.png">

This is my results:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/8356424/148590323-7e0c405a-8716-4767-b9d3-2db08b6b3d27.png">

**Comment by fgo-ableton** [comment]
The result looks nice! 
I actually thought more in the direction of regularly scheduling upcoming ticks for some small time interval (100ms or so). But this makes sense too.

**Comment by ndonald2** [comment]
Confirming that a well-tuned PLL tracking the link timeline is _highly_ effective for regulating and smoothing tempo changes in a pulse-clock output. I was able to engineer a solution using the general concept illustrated by @mathiasbredholt in the Pd patch screenshot. Thanks for sharing, this was a very helpful thread!
