### ISSUE TITLE
Handling phase

### ISSUE THREAD

**Issue by leehu** [Ableton/link#11]
One thing that I thought would be in the Link spec is a callback when a new bar was started. As it is, it seems as though it's up to us to poll this information and calculate when this has happened.

Is there any reason why this callback wasn't in the spec? thx

**Comment by brs-ableton** [comment]
We never really considered such a callback, so I can't give you a reason why it's not there. But it doesn't seem to me to be really necessary. In the absence of a tempo change, you can reliably predict quantum boundaries well into the future via the timeline methods. So if you want to get a callback at the boundaries you could set a timer for the next boundary and reset that timer in every callback to be invoked at the following quantum boundary. Tempo changes do trigger a callback, so you could also reset your timer against the new tempo whenever it changes.

Hope this helps.
