### ISSUE TITLE
Version String

### ISSUE THREAD

**Issue by abique** [Ableton/link#113]
Hi,
I think it'd be cool to have a version string somewhere.
So we could display in the software "built with Ableton Link version XXX".
What do you think?
Alex.

**Comment by fgo-ableton** [comment]
Hi,
I am not sure this would actually be used a lot.
Why not use the commit hash or the release tag?

**Comment by abique** [comment]
This is true, the hash would be a way to display it, but it would not be very meaningful to the user.
I've started to display those version strings in bitwig's dashboard > about.
Up to you, if you decide against it, then I'll use the git revision hash.

**Comment by fgo-ableton** [comment]
Ja. For the user the hash is not useful.
Anyways, until this is requested more I'd rather not add it.

**Comment by abique** [comment]
Alright, then you may close the ticket I suppose.
By the way the latest tag is quite old already. Have you plans to tag a new version?
