### ISSUE TITLE
Compilation fails with -fno-rtti - requires Asio submodule update

### ISSUE THREAD

**Issue by noizebox** [Ableton/link#117]
If Link is included in a project that is compiled with gcc using the flag --no-rtti, then compilation of Link fails with the following error. As the asio version used requires runtime type information and cannot be configured using the ASIO_NO_TYPEID macro. 

```
/home/gustav/workspace/sushi/third-party/link/modules/asio-standalone/asio/include/asio/execution/any_executor.hpp: In static member function ‘static const std::type_info& asio::execution::detail::any_executor_base::target_type_ex()’:
/home/gustav/workspace/sushi/third-party/link/modules/asio-standalone/asio/include/asio/execution/any_executor.hpp:850:21: error: cannot use ‘typeid’ with ‘-fno-rtti’
  850 |     return typeid(Ex);
```

This is really an Asio problem and from what I can tell was solved in v 1.18.1, see https://github.com/chriskohlhoff/asio/issues/533 and fix in https://github.com/chriskohlhoff/asio/pull/541
Updating the asio_standalone submodule in Link to the _asio-1-18-1_ tag makes it compile fine. Though it would be nice if the Asio version used in Link could eventually be updated to support this. Updating Asio to 1.18.1 doesn't break any other code and all tests in LinkCoreTests and LinkDiscoveryTests still pass, so it looks reasonably safe to update.

**Comment by fgo-ableton** [comment]
Hey. Thanks for reporting this. I updated the asio submodule: https://github.com/Ableton/link/commit/5820dbe0f2bef12691a7a2b2cbd4f6db1a74e3a9

**Comment by noizebox** [comment]
Wow, that was quick. Thank you very much.
