### ISSUE TITLE
Readme mention catch submodule

### ISSUE THREAD

**Issue by JoergAtGithub** [Ableton/link#118]
In the README.md it's mentioned, that: "Link relies on asio-standalone and catch as submodules"

But the catch gitmodule depedency seems to be removed since: https://github.com/Ableton/link/commit/3467470e558336990f7d554a81d476b6a5686f3b

**Comment by fgo-ableton** [comment]
Thanks for reporting! I pushed a fix: https://github.com/Ableton/link/commit/cf3f1f46f2da799ffa9264b5332bd785447301af
