### ISSUE TITLE
Link doesn't compile with Cxx20

### ISSUE THREAD

**Issue by JoergAtGithub** [Ableton/link#119]
If I `set(CMAKE_CXX_STANDARD 20)` in a project which includes Link, the build fails with:
`include\ableton\discovery\PeerGateways.hpp(38): error C2039: 'result_of': is not a member of 'std'`
because `std::result_of` was removed in C++20: https://en.cppreference.com/w/cpp/types/result_of

**Comment by cdi-ableton** [comment]
Hello, thanks for bringing this up. Could you please replace `using Gateway = typename std::result_of<Ga...` in `PeerGateways.hpp` with
```
using Gateway = decltype(std::declval<GatewayFactory>()(std::declval<NodeState>(),
    std::declval<util::Injected<IoType&>>(),
    std::declval<asio::ip::address>()));
```
and check if this works for your project.

**Comment by JoergAtGithub** [comment]
I checked this, it compiles now with `set(CMAKE_CXX_STANDARD 20)` and Link seems to work (found other devices and synced tempo).
Thank you!

**Comment by cdi-ableton** [comment]
Thanks for testing. I pushed a commit that should resolve the issue then: 8bbd58f5c723417760a291bc7820f2cfb1348c38
