### ISSUE TITLE
Novice computer science student looking to contribute

### ISSUE THREAD

**Issue by besartaliju** [Ableton/link#12]
Hello everyone! How are you? I'm a Computer Science student and Ableton lover. I would really like to contribute to Link now that it is open source. However, I am not really sure where to begin. Does anyone have any tips on how to contribute or what exactly to do?

My apologies if this is kind of a redundant question. I was more so looking for tips from the direct people who are contributing rather than a vague article.

Thank you,
Besart

**Comment by fgo-ableton** [comment]
Hey Besart,
thanks a lot for your interest!
I'd suggest starting by using Link in some project. If something comes up there let us know!
