### ISSUE TITLE
SessionState.hpp is missing include for <std::mutex>

### ISSUE THREAD

**Issue by triplef** [Ableton/link#125]
I’m getting the following error building v3.0.5 on Windows using Clang:

```
SessionState.hpp(88,16): error: no type named 'mutex' in namespace 'std'
	  mutable std::mutex mMutex;
	          ~~~~~^
```

Adding `#include <mutex>` to SessionState.hpp fixes the issue.

**Comment by fgo-ableton** [comment]
Thanks for reporting this! I just pushed a fix.
