### ISSUE TITLE
AudioEngine.cpp Warning=Error: variable is not used

### ISSUE THREAD

**Issue by JoergAtGithub** [Ableton/link#127]
The following occurred not for myself - it was reported to VCPKG package manager project. I just relay it, because I think this should be fixed upstream:
https://github.com/microsoft/vcpkg/pull/28480

**Comment by cdi-ableton** [comment]
Thanks for pointing this out. This was fixed with abc93d98ab830d2a917e36e2f8d34623b3fbfecc. We've just released [`3.0.6` ](https://github.com/Ableton/link/releases/tag/Link-3.0.6) which includes this commit.

**Comment by JoergAtGithub** [comment]
Great. Thanks!
