### ISSUE TITLE
QLinkHut segfaults when clicking on 'Play' (jack)

### ISSUE THREAD

**Issue by umlaeute** [Ableton/link#17]
I'm building current HEAD (d4fb22b), on _Debian/sid (amd64)_ (with g++-6, ignoring the issue #16  for now), including the QT examples, and have manually enabled JACK support:

```
$ mkdir build
$ cd build
$ cmake -DLINK_BUILD_QT_EXAMPLES=ON -DLINK_BUILD_JACK=ON ..
$ make -j -k
[...]
$
```

This gives me `LinkHut`, `QLinkHut` and `QLinkHutSilent` in `bin/`)
- running `bin/LinkHut` seems to work 
  - i get audible clicks
  - keystrokes work
  - running multiple instances, they sync
- running `bin/QLinkHutSilent` seems to work as well
  - i get _no_ audible clicks (expected)
  - clicking on <kbd>Link</kbd> i get `0 Links` or `1 Links` depending on the existance of other `(Q)LinkHutSilence` instances
  - instances sync
  - clicking on <kbd>Play</kbd> i see a colourful beat visualisation
- running `bin/QLinkHut` _almost_ works
  - i get no audible clicks
  - clicking on <kbd>Link</kbd> i get `0 Links` or `1 Links` depending on the existance of other `(Q)LinkHutSilence` instances
  - instances sync
  - clicking on <kbd>Play</kbd> i get a segfault :cry: 

```
$ gdb ./bin/QLinkHut
(gdb) run
Starting program: /foo/bar/ableton-link/build/bin/QLinkHut 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee96d700 (LWP 12022)]
[New Thread 0x7fffee16c700 (LWP 12023)]
[New Thread 0x7fffed96b700 (LWP 12024)]
[New Thread 0x7fffed8ea700 (LWP 12025)]
[New Thread 0x7fffed869700 (LWP 12026)]
[New Thread 0x7fffe1810700 (LWP 12028)]
[New Thread 0x7fffd840f700 (LWP 12029)]
[New Thread 0x7fffd7c0e700 (LWP 12030)]
[New Thread 0x7fffd740d700 (LWP 12031)]
[New Thread 0x7fffd6c0c700 (LWP 12032)]
[New Thread 0x7fffd61d3700 (LWP 12033)]
[New Thread 0x7fffd48f7700 (LWP 12034)]

Thread 6 "QLinkHut" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed869700 (LWP 12026)]
0x00007ffff77bcfe0 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
(gdb) bt
#0  0x00007ffff77bcfe0 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#1  0x00007ffff77bd7c1 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x0000555555730d25 in ableton::linkaudio::AudioPlatform::audioCallback(unsigned int) ()
#3  0x0000555555730c2e in ableton::linkaudio::AudioPlatform::audioCallback(unsigned int, void*) ()
#4  0x00007ffff77ba01e in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#5  0x00007ffff77b97e8 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#6  0x00007ffff77d1040 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#7  0x00007ffff7591464 in start_thread (arg=0x7fffed869700) at pthread_create.c:333
#8  0x00007ffff5bdf9df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

**Comment by fgo-ableton** [comment]
Thanks. I also noticed yesterday. Did not notice before because it worked for buffer sizes <= 512. Should be fixed now.
