### ISSUE TITLE
fails to compile on any unix-non64bit architecture

### ISSUE THREAD

**Issue by umlaeute** [Ableton/link#18]
building the 1.0.0 release for Debian, we find that ableton-link fails to compile on all non-64bit architectures (and on some 64bit architectures as well):

| architecture | status |
| --- | --- |
| amd64 | Installed |
| arm64 | Build-Attempted |
| armel | Build-Attempted |
| armhf | Build-Attempted |
| i386 | Build-Attempted |
| mips | Build-Attempted |
| mips64el | Build-Attempted |
| mipsel | Build-Attempted |
| powerpc | Build-Attempted |
| ppc64el | Installed |
| s390x | Installed |
| alpha | Build-Attempted |
| hppa | Build-Attempted |
| hurd-i386 | Failed |
| kfreebsd-amd64 | Build-Attempted |
| kfreebsd-i386 | Build-Attempted |
| (m68k | Needs-Build) |
| (powerpcspe | Needs-Build) |
| (ppc64 | Needs-Build) |
| (sh4 | BD-Uninstallable) |
| sparc64 | Installed |
| x32 | Build-Attempted |

[Debian#642410](https://bugs.debian.org/#842410) suggest that this is due to the default `LINK_WORD_SIZE=64` and the resulting use of `-m64`.

So my main question is, why does the build require the `-m64` (resp. `-m32`) flags by _default_? Shouldn't most compilers have sane defaults?

**Comment by fgo-ableton** [comment]
That should be fixed on the current master head. We haven't made a new release yet. Could you check if you run into issues with the current version?

**Comment by umlaeute** [comment]
ah, i see 31a8e4ecbaad7fafe542ccb9bd53373133cab52e
this should indeed fix it.
i'll check asap.

**Comment by umlaeute** [comment]
this has been fixed a long time ago.
sorry for not coming back earlier...
