### ISSUE TITLE
Get Beat syncing worked in Console

### ISSUE THREAD

**Issue by ItsCoding** [Ableton/link#22]
Hi everyone , i have a short question :)
How Can i make an Application with Link integreated that prints Out a Line to Console every time my Main Computer so the DJ Controller makes a Beat so from the BPM Line... Can someone help me with it i am Not best c++ Developer :D

**Comment by nre-ableton** [comment]
Hi @ItsCoding, you should have a look at the [linkhut demo][1], which is a command-line app that demonstrates the basic functionality of Link.


[1]: https://github.com/Ableton/link/blob/master/examples/linkhut/main.cpp

**Comment by ItsCoding** [comment]
Okay i got compiled the example but i always dont understand how to GET the beats from abletone and not to send it ... actually i understand that the LinkHut demo only sends beats and wont recive it

**Comment by abique** [comment]
Maybe we can close this issue?

**Comment by nre-ableton** [comment]
@ItsCoding Have a closer look at the `printState` function in that example. The tempo is shown by accessing it from the `timeline.tempo()` method. However, you will need to do a bit of work to try to get it to print out a line every time a beat is sent.

In the example code, there is simply a `while` loop that sleeps and then prints out the tempo at regular intervals. You could modify this to set the sleep period to align with the next beat, but of course you'll have to recalculate that value if the tempo changes.

It's important to note that Link does not work like MIDI sync. It is not sending out beat (or, to be exact, PPQ) events on a regular basis -- only when something changes like the tempo or number of peers. So if nothing changes you can print out the beats at regular intervals.
