### ISSUE TITLE
Revision bbb6aa83c3ad5026e2da56a63e3047f5a01f6a41 seems to be broken (on Linux?)

### ISSUE THREAD

**Issue by abique** [Ableton/link#24]
Hi,

link examples were unstable for me on Linux.

I compiled the master branch of Link and built it in release mode.
Every tests passes.

Then I opened two terminals on the same computer, both using jack for the audio output.
Then I started LinkHut twice and let it play for a few minutes, clicks where on time, then I started to increase and decrease the tempo and at some point one of the LinkHut stopped to play.

Is it a known issue?

Alex.

**Comment by abique** [comment]
```
17-02-02 14:09:12 abique@galactic-ship:~/d/a/l/b/bin git:(HEAD> uname -a
Linux galactic-ship 4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64 GNU/Linux
17-02-02 14:09:19 abique@galactic-ship:~/d/a/l/b/bin git:(HEAD> gcc --version
gcc (GCC) 6.3.1 20170109
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


```

**Comment by ala-ableton** [comment]
Hi Alex,

Thanks for the report.

What is the last commit on `master` that is not broken for you? That would help us figure out which change might be responsible.

Alain.

**Comment by abique** [comment]
Hi Alain, I'm bisecting.

**Comment by abique** [comment]
This commit seems to be working so far: 8b4edf89b1903cecc35e5b2a2c1e95752de47a8a

**Comment by ala-ableton** [comment]
@brs-ableton, @cdi-ableton: please have a look

**Comment by abique** [comment]
By the way on Linux, the clock should be using clock_gettime(CLOCK_REALTIME, ...).
Because with ALSA when you want to know the time at which a sample will be played, it is in the CLOCK_REALTIME reference.

**Comment by abique** [comment]
Pull request incoming for proper clock on Linux.

**Comment by abique** [comment]
Pull request sent, and with it, it works so far.

**Comment by abique** [comment]
I got linkhut to have a huge negative beat time just by playing with the tempo. Master seems badly broken here, does it work well for you?

**Comment by abique** [comment]
![screenshot_20170203_084732](https://cloud.githubusercontent.com/assets/31200/22590789/311423b8-ea11-11e6-9777-724d4426a733.png)

**Comment by cdi-ableton** [comment]
@abique So changing the clock (#25) didn't work for you?

I have no problems running two instances of QLinkHut on my machine: `Linux reiko 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I did tests with `ALSA` as well as `JACK`.

**Comment by abique** [comment]
@cdi-ableton no it did not fix it for me.
At first sight it looks like it works but after some time of letting it play and aggressively changing the tempo, I can get some drops: some clients of the session stops playing.

Also as you can see in the screenshot something must have gone wrong to show such a negative beats right?

**Comment by cdi-ableton** [comment]
@abique There is a problem with using Link's current STL clock as well as the `CLOCK_REALTIME` that you are proposing. The clock used by Link must be monotonic. The `CLOCK_REALTIME` is not monotonic since it is affected by NTP. So it can move forwards and backwards. The `high_resolution_clock` that Link is using can be monotonic but it's not guaranteed.

Could you please check if the STL clock is monotonic on your machine by adding this static assert to `stl/Clock.hpp`: `static_assert(high_resolution_clock::is_steady, "clock is not monotonic");`

**Comment by abique** [comment]
@cdi-ableton I know that CLOCK_MONOTONIC is better, but the fact is that many syscalls only supports the realtime clock. So you might not be able to use CLOCK_MONOTONIC at every steps of the process. See sem_timedwait for example.

Why not add the assertion to the stl clock? If it is a strong requirement to be monotonic then it should not build if it is not.

**Comment by abique** [comment]
I asked for help to the glibc regarding the sem_timedwait and CLOCK_REALTIME.

https://sourceware.org/ml/libc-help/2017-02/msg00015.html

**Comment by cdi-ableton** [comment]
Because Link requires a monotonic clock its STL clock should use the `std::chrono::steady_clock` instead of `std::chrono::high_sesolution_clock`. The latter is just an alias for `std::chrono::system_clock` or `std::chrono::steady_clock`. I looked at the source code of LLVM and GCC. Both using `CLOCK_MONOTONIC` for `std::chrono::steady_clock`.

Would you be up for running another test with LinkHut using `std::chrono::steady_clock` instead of `std::chrono::high_sesolution_clock`? I'd be interested if this solves the weird beattime jump problem you're having.

Great that you already got details regarding `sem_timedwait`.

**Comment by abique** [comment]
As you found, the static_assert fails on Linux with high_resolution_clock.

**Comment by abique** [comment]
I did a few tests with the clock monotonic and I think some clients lost sync.
So I'm doing a new one, more serious.

![screenshot_20170217_095619](https://cloud.githubusercontent.com/assets/31200/23058998/bca11b2a-f4f7-11e6-8a61-d8fd6dc70d9b.png)

As you can see in the screenshot I start all the client almost at the same time and the bpm was 20, so the beat time should always be close between each other.

Now I will rase the tempo, and let it run for a few hours and I'll post a screenshot again.

**Comment by abique** [comment]
![screenshot_20170217_100748](https://cloud.githubusercontent.com/assets/31200/23059270/fb4111d6-f4f8-11e6-9ef0-8ca1c8b41d8f.png)

It already lost sync a few times, in less than 7 minutes.

**Comment by abique** [comment]
Do you have any idea on what could happen? It is not a clock issue as this test was run using CLOCK_MONOTONIC. It is not a network issue, as everything is ran in the same host.
Also after raising the tempo in the previous test, the tempo did not change either, so I believe this is optimal conditions for link.

**Comment by cdi-ableton** [comment]
Yes, this should definitely work. Can you confirm that the beat times were all the same right after the tempo change?

**Comment by abique** [comment]
They were very close.

**Comment by cdi-ableton** [comment]
Within the range of the Quantum of 4 beats?

**Comment by abique** [comment]
Yes, I did not touch the Quantum.

I believe that you are in Berlin, maybe one day we could meet and do some testing together? I would bring my laptop with Linux on it.

**Comment by cdi-ableton** [comment]
One explanation for this beat time offset could be that some LinkHuts loose connection during the tempo change and do a tempo jump after the connection is re-established. If the time of disconnection is long enough they could be off by a quantum or even a couple of quanta but still be in phase. The LinkHuts in your test are all off by multiples of a quantum I think. So I'd be interested if this is already the case immediately after you changed the tempo or not.

Yes, I'd be up for a meeting.

**Comment by abique** [comment]
I would suggest Friday 3 march, we can meet for lunch and hack/test during the afternoon? Would that be good for you?

You can contact me by mail: bique.alexandre@gmail.com

**Comment by cdi-ableton** [comment]
Works for me. I'll contact you.

**Comment by cdi-ableton** [comment]
Please check out the latest commit (b3b3445b8e47edfb9583aea970a8bc75106fd1be). It should solve the offset problem. It turned out that it wasn't mainly a clock issue in this case and therefore could happen on other platforms too. Since the STL clock that we were using could also cause such a behaviour I changed it as well.

**Comment by abique** [comment]
Hi,
I started a new test with that commit, and it looks better :+1:

**Comment by abique** [comment]
Hi,

So it is much better than before, but I could manage to get one drift in less than an hour:

![screenshot_20170328_102528](https://cloud.githubusercontent.com/assets/31200/24395751/f5ccbeaa-13a0-11e7-92df-a78d24a8c0e5.png)

Alex

**Comment by cdi-ableton** [comment]
Thanks for testing! Were the LinkHuts running with 20 Bpm all the time?

**Comment by abique** [comment]
No, I did change the tempo a few times. It ran at 140 most of the time.

**Comment by cdi-ableton** [comment]
If there are really fast and big tempo changes applications can diverge by a multiple of a quantum. Link guarantees that the phase is always in sync for participants with the same quantum.

What should work with the current commit is that applications running on the same machine that start with the same beat time should not diverge when not changing the tempo drastically (like ramp from 999 to 20 in a millisecond).

In my tests I ran ~10 LinkHuts, started playback at 20 Bpm to guarantee that they all start at the same beat time, ramped up the tempo to ~300 Bpm and occasionally checked if the beat times diverged.

**Comment by abique** [comment]
OK, so let's close the bug.
If get I new issues I'll open a new one.

Many thanks to all the team!

Alex.

**Comment by cdi-ableton** [comment]
Thanks for the severe testing!

**Comment by abique** [comment]
My pleasure ;-)
