### ISSUE TITLE
-m64 is present in Raspian build and this flag is not valid

### ISSUE THREAD

**Issue by leehu** [Ableton/link#3]
Build works fine without the flag so just needs to be omitted from make file generation

**Comment by fgo-ableton** [comment]
Yes, the default is 64 bit. Configuring with `cmake -DLINK_WORD_SIZE-32 ..` should do the trick for now.

**Comment by leehu** [comment]
Hi, this option is not valid at all for gcc on Linux it appears - certainly not on the one shipped on Pi - so it needs to be removed completely - the build works fine if there is no '-m' option specified

**Comment by fgo-ableton** [comment]
Thanks for clarifying. CMake no longer adds the `-m` flag.  https://github.com/Ableton/link/commit/31a8e4ecbaad7fafe542ccb9bd53373133cab52e
