### ISSUE TITLE
Additional dependencies required for Rasbpian

### ISSUE THREAD

**Issue by leehu** [Ableton/link#4]
portaudio needs to be installed on pi - I've installed this on jessie and all works fine.

sudo apt-get install portaudio19-dev

For some reason there are dependency problems so the user will also need to install the jackaudio packages listed.

**Comment by fgo-ableton** [comment]
Thanks for pointing that out.

**Comment by leehu** [comment]
Ah yes, so it is - missed that... I guess it's not really Optional though?

**Comment by fgo-ableton** [comment]
I changed that section in the Readme a little. It is aimed to list the dependencies for Link itself. Portaudio is optional as it is only required for the example apps. I hope this is clearer now.
