### ISSUE TITLE
Getting quantum without AudioPlatform on a non-audio application

### ISSUE THREAD

**Issue by toxnico** [Ableton/link#46]
Hi there,

I'm working on an application (Linux, Windows, MacOS) that synchronizes to Link and doesn't need to produce any sound. Actually it drives a microcontroller to display information.

Thanks to the LinkHut sample project, I managed to get almost all the information I need (tempo in bpm, beat count).

But I can't figure out how to get the quantum a simple way (I mean beat signature, like **_4_**/4, **_5_**/4 and so on).

Oh well, Of course I could mimic LinkHut and integrate the AudioEngine/AudioPlatform in my app, but isn't there a lightweight method to obtain this value from the Timeline object for example? I'd like to be as audio-driver-independant as possible.

Many thanks for your help,

Nico

**Comment by fgo-ableton** [comment]
The quantum is not a value that is provided by Link. Every peer in a link session can choose it's own quantum. The concept is described in the _Beat Alignment_ and _Phase Synchronization_ sections on http://ableton.github.io/link/
So you can either choose a constant beat time for your app, or provide some UI for the user to change it.

**Comment by toxnico** [comment]
Oh okay, I didn't notice this in the documentation page. I'll go the UI way then!

Thanks for your answer, I'm closing this topic.

Nico
