### ISSUE TITLE
Integrating Link with a project with higher mininum Windows version

### ISSUE THREAD

**Issue by brianlheim** [Ableton/link#47]
One of the projects I work on is attempting to integrate the Link library into the codebase, and we're running into problems because the project requires Win API functions introduced in Vista, but the CMake config file for this project adds compile flags to compile for XP support.

A log of the build is here. `CancelIoEx` and `SHGetKnownFolderPath` are Vista API functions.

https://ci.appveyor.com/project/brianlheim/supercollider-mu8dk/build/305/job/98e3uw5u2upo93oo

From what I understand the flags are propagated from the AsioStandalone lib as configured in this cmake file: https://github.com/Ableton/link/blob/master/cmake_include/AsioStandaloneConfig.cmake

CMake is a bit confusing to us, so we're not sure if there's a way to get around this on our end or your end without changes to the code itself. Any guidance you can provide on how best to do this integration would be very much appreciated.

Thanks!

**Comment by ala-ableton** [comment]
`AsioStandaloneConfig.cmake` is adding `_WIN32_WINNT` to the pre-processor macros to avoid warnings from [`asio/include/asio/detail/config.hpp`](https://github.com/chriskohlhoff/asio/blob/722f7e2be05a51c69644662ec514d6149b2b7ef8/asio/include/asio/detail/config.hpp#L720-L730). However, setting `_WIN32_WINNT` could be done in `AsioWrapper.hpp` instead of `AsioStandaloneConfig.cmake` to support cases where `_WIN32_WINNT` is already defined.

```diff
diff --git a/cmake_include/AsioStandaloneConfig.cmake b/cmake_include/AsioStandaloneConfig.cmake
index ef9a211..3e4720c 100644
--- a/cmake_include/AsioStandaloneConfig.cmake
+++ b/cmake_include/AsioStandaloneConfig.cmake
@@ -8,7 +8,6 @@ set_property(TARGET AsioStandalone::AsioStandalone APPEND PROPERTY
 if (WIN32)
   set_property(TARGET AsioStandalone::AsioStandalone APPEND PROPERTY
     INTERFACE_COMPILE_DEFINITIONS
-    _WIN32_WINNT=0x0501
     _SCL_SECURE_NO_WARNINGS
   )
 endif()
diff --git a/include/ableton/platforms/asio/AsioWrapper.hpp b/include/ableton/platforms/asio/AsioWrapper.hpp
index db9d665..e220217 100644
--- a/include/ableton/platforms/asio/AsioWrapper.hpp
+++ b/include/ableton/platforms/asio/AsioWrapper.hpp
@@ -37,6 +37,12 @@
 #define INCL_EXTRA_HTON_FUNCTIONS 1
 #endif

+#if defined(WIN32) || defined(_WIN32)
+#if !defined(_WIN32_WINNT)
+#define _WIN32_WINNT 0x0501
+#endif
+#endif
+
 #if defined(__clang__)
 #pragma clang diagnostic push
 #if __has_warning("-Wcomma")
```

@fgo-ableton what do you think about this?

**Comment by fgo-ableton** [comment]
Hey @brianlheim, could you check if [this branch](https://github.com/Ableton/link/tree/win32) works for you.

**Comment by brianlheim** [comment]
That appears to work, thank you so much! [build log](https://ci.appveyor.com/project/brianlheim/supercollider-mu8dk/build/311/job/l0nl2ba6y6kbu48y)

**Comment by fgo-ableton** [comment]
Cool, I merged the changes. Looking forward to Link in SC!

**Comment by brianlheim** [comment]
Thanks! I appreciate the quick response. :)
