### ISSUE TITLE
Add JACK support to example applications

### ISSUE THREAD

**Issue by rncbc** [Ableton/link#6]
Add new LINK_BUILD_JACK option to build example applications with JACK support on Linux (http://jackaudio.org). 

See #5. -- I reckon you're not accepting pull-requests at this time, but it goes anyway for reference purposes. thanks.

**Comment by fgo-ableton** [comment]
@rncbc Have you seen the update in [CONTRIBUTING.md](https://github.com/Ableton/link/blob/master/CONTRIBUTING.md)?

**Comment by rncbc** [comment]
On 10/05/2016 09:11 AM, Florian Goltz wrote:
> @rncbc <https://github.com/rncbc> Have you seen the update in
> CONTRIBUTING.md
> <https://github.com/Ableton/link/blob/master/CONTRIBUTING.md>?
>

no. the PR is prior to the update.

anyway, i've just emailed the signed CLA and now i believe this PR 
meets all the requirements stated in 
https://github.com/Ableton/link/blob/master/CONTRIBUTING.md .

cheers
-- 
rncbc aka. Rui Nuno Capela
