### ISSUE TITLE
Tempo changes with large latency compensation values

### ISSUE THREAD

**Issue by jamshark70** [Ableton/link#60]
I'm working on Link integration for SuperCollider. (Another developer, smiarx, did most of the work; I'm fixing up latency compensation and a couple of other issues.)

I'm struggling with the interaction between tempo changes and latency compensation.

Here's a test scenario.

- Peer 1: Tempo = 60, for argument's sake assume initially that beats == seconds, latency 250 ms.
- Peer 2: Tempo = 60, assume initially that beats == seconds, latency 100 ms.

Sec | P1 beats | P2 beats | Event
----|----------|----------|------
9.75 | 10 | 9.85 | P1: Note on
9.78 | 10.03 | 9.88 | P2: Tempo change to 160
(x) | 10.1 | 9.95 | P1: Note off

(Sec and P1/P2 beats might look a little strange. In SC, the client-side clock needs to run earlier than the audio. Then, a latency offset is added to the OSC bundle timestamp so that the audio hits the wire at "now" [logical time] + latency. Secs 9.75 + latency 0.25 = hear it at 10.0 secs. In practice, on my Linux box, SC seems to need a minimum of 0.07 or 0.08 seconds OSC messaging latency.)

In theory, after the tempo change, the timeline's timeOrigin should correspond to 9.78 seconds -- therefore (x) should be 0.07 beats * secsPerBeat + timeOrigin = 0.07 * 3/8 + 9.78 = 9.80625.

I'm finding in practice that the link timeline is calculating a seconds value for the note-off that is exactly 100 ms *before* the note-on (???!!!), leaving a stuck note.

```
latency 0.25	SysClock logical time 77.10222	thisThread's logical time 49.0
	[ 9, 'default', 1004, 0, 1, 'out', 0, 'freq', 261.6255653006, 'amp', 0.1, 'pan', -1 ]

latency 0.25	SysClock logical time 77.00222	thisThread's logical time 49.1
	[ 15, 1004, 'gate', 0 ]

FAILURE IN SERVER /n_set Node 1004 not found
```

- Should be: note-on 77.10222, note-off 77.15847
- Is: note-on 77.10222, note-off 77.00222

P2 sets the tempo like this -- is this correct?

```
void LinkClock::SetTempoAtBeat(double inTempo, double inBeats)
{
	auto timeline = mLink.captureAppTimeline();
	// secs should subtract mLatency here
	// I'd rather do timeAtBeat() - mLatency,
	// but I haven't found the right answer at stackexchange yet
	auto time = timeline.timeAtBeat(inBeats - (mLatency * mTempo), mQuantum);
	timeline.setTempo(inTempo*60., time);

	mTempo = inTempo;
	mBeatDur = 1. / inTempo;

	mLink.commitAppTimeline(timeline);
	mCondition.notify_one();
}
```

In theory, inBeats should be 9.88, mLatency = 0.1, mTempo = 1, so `timeAtBeat` should be returning the value for 9.78, and I would expect, then, that the timeline's timeOrigin should match.

And P1 receives the tempo via a callback. Here, we should probably get `secs` from the timeline. But `beats` is used only for a callback into the SC language -- it isn't used to modify the timeline's state, so it shouldn't matter for this test case.

```
	mLink.setTempoCallback([this](double bpm) {
		double secs = elapsedTime();
		double tempo = bpm / 60.;

		auto timeline = mLink.captureAppTimeline();
		// I am not sure if `+ latency` is right here
		double beats = timeline.beatAtTime(hrToLinkTime(secs + mLatency), mQuantum);

		mTempo = tempo;
		mBeatDur = 1. / tempo;
		mCondition.notify_one();

		... SC-specific callback, doesn't affect audio...
	});
```

So... what am I doing wrong?

TIA.

**Comment by jamshark70** [comment]
Hm, on second thought, `SetTempoAtBeat` shouldn't subtract latency. That was a shot in the dark to fix it after the initial version (which doesn't subtract) failed.

As I think about it further: "beat 9.88" in P2's timeline should correspond to beat 9.88 in P1's timeline, and beat 9.88 in any other peer's timeline. "9.78" is a SC implementation detail that should be independent of musical content.

But I still get the note-off coming early -- just, less early. (Curiously, it's 0.0375 beats earlier than the note-on. 0.0375 = tempo (0.375 bps) * note dur (0.1). Weird.)

```
latency 0.25	SysClock logical time 58.66659	thisThread's logical time 40.0
	[ 9, 'default', 1003, 0, 1, 'out', 0, 'freq', 261.6255653006, 'amp', 0.1, 'pan', -1 ]

latency 0.25	SysClock logical time 58.62909	thisThread's logical time 40.1
	[ 15, 1003, 'gate', 0 ]
```

... which brings me to a point I had thought through some months ago, but not quite remembered until now.

Peers with large latency-compensation requirements need to be made aware of tempo changes before they happen.

That is, now, I think the real problem in my test case is: the tempo change is scheduled for 0.12 beats before the note-on beat -- so, at the initial tempo of 1, P1 needs to process the tempo change 0.12 seconds before it processes its note-on = 9.63 sec. But P2 hasn't even generated the tempo change yet.

To handle it really properly, then, Link should have a way to specify a future tempo change, which peers can query and prepare for, according to their own latency-compensation needs.

**Comment by jamshark70** [comment]
I believe I've found a workaround in SC. There will be slight inaccuracy at the moment of tempo change, but it should recover quickly. So I'll close this.

**Comment by fgo-ableton** [comment]
Link does not offer scheduling. As soon as a SessionState is committed it will be sent to the network. Theoretically it would be possible to schedule committing the on SCs side. But that sounds tricky to me.
Inaccuracies during a tempo change are ok. In practice they are not even perceivable most of the time. Eventually when the tempo is constant again all peers will align.

**Comment by jamshark70** [comment]
I tested an approach that checks whether the "seconds" value coming from Link is less than the previous "seconds," and if so, it uses `lastSeconds + ((beats - lastBeats) * beatDur)`. `beats` are guaranteed to be increasing always, so this guarantees that every "seconds" value for a scheduled event is >= the previous one. So the problem with stuck notes disappears.

I'm satisfied with this -- no action needed. Thanks for the explanation.
