### ISSUE TITLE
Link crashing on Android with Qt?

### ISSUE THREAD

**Issue by sinosoidal** [Ableton/link#62]
I'm having a crash every time I set Link enable(true) on Android. The same doesn't happens on Windows, Mac and iOS. I use Qt to develop all my apps. This is what I get on the console output by the time of the crash:

```
F libc    : stack corruption detected
F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 13715 (qtMainLoopThrea)
```

Have you ever had any similar behaviour?

**Comment by cdi-ableton** [comment]
This sounds familiar. Please have a look at #35.

**Comment by sinosoidal** [comment]
@cdi-ableton indeed! The solution here. Thanks!! 👍
