### ISSUE TITLE
[sc] Synchronizing quantum changes across multiple peers

### ISSUE THREAD

**Issue by jamshark70** [Ableton/link#65]
In SuperCollider, I have been experimenting with synchronizing meter (quantum) changes. I find I can get it to work only about 10% of the time. Not quite a happy success rate.

My goal is: Issue some statement in one SC client to change the meter on the next barline, and have all connected SC peers changed to the same meter on their own next barlines.

What seems to be happening instead is that the SC client originating the meter change instantaneously reevaluates its Link phase WRT other peers, and then becomes either one beat early, or it drops an entire bar and is late after that.

I'm not sure if it makes a difference, but for early tests, I'm running both SC instances on the same machine (so they are following the same physical clock timing).

- Instance A, when it changes meter, sends an OSC message to other SC instances telling them to change meter.

- Instance B has an OSC responder that changes meter on the next bar.

Both instances are using `clock.nextBar` as the time point for the meter change. When starting LinkClocks, SC *does* correctly synchronize phase.

I've gotten three different types of results:

- If I start the two clocks within about one second, everything seems to work. The two clocks' beat counters are totally in sync.

- If I start B, then A about 1-2 seconds later, then the beat counters appear to be in sync, but something is different internally because A sleeps for a bar. At 60 bpm, beat 16 should be one second later, but it's *four* seconds later: beat 15 = 2535.x, beat 16 = 2539.x???

```
// clock beat counter, beat within bar (Link phase), logical seconds
[ 15.0, 3.0, 2535.327133 ]
set meter at beat: 16.0
sending: [ linkMeter, 3, 16, 1 ]
[ 16.0, 0.0, 2539.327133 ]  <<-- HERE
```

- If I start A 2-4 seconds later, then A's beat counter initially is B's beats - 4. Then the meter change causes it to skip a beat: beat 20 is at the same physical time as beat 19.

```
[ 19.0, 3.0, 2209.414311 ]
set meter at beat: 20.0
sending: [ linkMeter, 3, 20, 1 ]
[ 20.0, 0.0, 2209.414311 ]  <<-- HERE
[ 21.0, 1.0, 2210.414311 ]
```

In all of my tests, instance B shows no timing disruption -- probably because, when it updates its own quantum, the new quantum agrees with the other peer's quantum.

It's possible that SC is handling the quantum incorrectly.

I'm not sure what to do next. Advice?

**Comment by jamshark70** [comment]
Also note: My initial approach was --

Instance A changes meter and quantum --> observer --> broadcast OSC --> Instance B receives and updates

I've changed that to:

- `changeMeter` function broadcasts OSC
- Instance A and B independently schedule meter/quantum changes for the next exact barline

No difference in results. I can easily reproduce incorrect relationships between beats and seconds.

It appears that changing quantum is just fundamentally broken.

**Comment by fgo-ableton** [comment]
The quantum is not maintained by Link or ever shared on the network. It is just a parameter used when mapping local host clock time to beat time. So it is even possible to capture one single SessionState and then query beat times for different quanta without having any impact on other peers or even changing the local state.
Also, Link does not assure that the timeline progresses the same amount of beats on all peers during the same time. It only makes sure the phases are aligned for the requested quantum. Changes to the state, either by changing tempo or forcing beat times are applied locally and then will later merge with other changes that might have been applied by other peers at the same time. 
So in the case you describe above where the clients are started more than a quantum apart from each other they will run with an offset of a quantum (or more) to each other.

So if you want to somehow synchronize quantum changes and make sure that the clients run in beat time sync, a possible approach would be to somehow schedule a point in time in the future (bar end) and do both, change the quantum and reset the timeline to a common beat time. This should result in peers running at the same quantum and same beat time.
However, if there are other peers on the network that change tempo in parallel, again there is no guarantee for all peers to align in the same way as this will depend on the order the network messages are handled by each peer.

**Comment by jamshark70** [comment]
As a composer, a fundamental modern-music use case is "everybody changes meter at the same time."

You seem to be confirming that Ableton Link cannot handle this.

From a musician's perspective, this is a rather serious deficiency.

**Comment by fgo-ableton** [comment]
Link was designed to help electronic musicians play in sync. It explicitly does not force all peers to use the same quantum. If musicians choose to change quantum at the same time (i.e. because they are following a score) Link allowd that.
There is no master or master timeline. This might be a deficiency for some use cases - but is really useful for others.

**Comment by jamshark70** [comment]
I apologize for being testy. The tone of my last reply was inappropriate.

I agree that it's useful to support polymeters, and I agree that it's useful for peers to be at different beat values while having phases in sync. These parts of it, I understand.

However, I'm observing with a simple change of quantum, even if I change it in only one peer, that one beat becomes 0, or 2 or 3 or 4 / beatsPerSecond seconds: when I change quantum, sync is immediately lost.

I'm pretty sure the issue is:

> and do both, change the quantum and *reset the timeline to a common beat time*

I'm unclear what to reset the timeline to. I'll take a guess that the SC clock should maintain a quantum-related offset to add/subtract to beats before/after conversion to/from seconds... is that close to the idea?

**Comment by fgo-ableton** [comment]
I'm sorry - I was wrong about the usage of reset - this won't help in your scenario. I'll explain in the new thread.
