### ISSUE TITLE
Extra build info for Pi

### ISSUE THREAD

**Issue by leehu** [Ableton/link#7]
Hi, gcc is still 4.x that comes with Raspbian (debian jessie) - if people want to build they'll need to upgrade to gcc-6. There are some instructions here on how to do it:

https://solarianprogrammer.com/2016/06/24/raspberry-pi-raspbian-install-gcc-compile-cpp-14-and-cpp-17-programs/

The build should be done with:
CC=gcc-6 CXX=g++-6 cmake ..
cmake --build .

Don't know if you want to add this to your build info somewhere...?

**Comment by fgo-ableton** [comment]
@leehu Thanks for collecting those infos. At the moment there is no CI service that allows testing for the pi. This makes it hard for us to maintain the the information and make sure it stays up to date. So I'd rather not add them here.
