### ISSUE TITLE
C API "compatibility" header

### ISSUE THREAD

**Issue by benswift** [Ableton/link#71]
I want to create language bindings for ableton link as a shared library, however the environment I'm working in can manage C linkage but not C++ (no de-mangler, etc). As I'm sure y'all know, often there's a "compatibility" header with enough typedefs (inside an `extern "C"`) to interop with the C++ library. However, I can't see one for this library.

The closest I can find is the `ABLLink.h` header in the [LinkKit](https://github.com/Ableton/LinkKit) project. That's not quite what I'm after---I still want it to be cross-platform, just with easy (dynamic) linking from C. Although obviously I could use that header as a starting point, replacing all the iOS-specific stuff (the usefulness of which is alluded to [here](https://github.com/Ableton/link/issues/52#issuecomment-441980100).

Is there some easier way to do this that I'm missing?

p.s. sorry about the word _link_ being overloaded in this issue, but that's on you I think 😉

**Comment by fgo-ableton** [comment]
There is no generic C API. But it should be relatively straight forward to create one.
What environment do you want to link from? 😄

**Comment by benswift** [comment]
Sure, no worries - as you say, it would be straighforward.

> What environment do you want to link from? 😄

It's this one: <https://extemporelang.github.io>

**Comment by resinbeard** [comment]
Very surprised at the pushback for a simple C api after being recognized in several closed threads that it would be useful. Must be one of those 'we only write C++ programs for Macintosh and Windows that are VST plugins written in JUCE' kind of shops.

**Comment by yaxu** [comment]
Hey @benswift, did you get anywhere with this?
I saw that Carla has such a header for its transport library https://github.com/falkTX/Hylia/blob/master/hylia.h

**Comment by benswift** [comment]
Hey @yaxu 😄 

I didn't really get anywhere - I found the iOS one as you did, but I came to the same conclusion that @falkTX did (I guess) and realised that the simplest way would be to write a small C header-only wrapper lib. And then life got in the way and I didn't end up actually _doing_ it.

I am still interested in it, though, and perhaps that Hylia lib is a good starting point.

**Comment by falkTX** [comment]
I cam do a proper release of https://github.com/falkTX/Hylia if there is interest on it.
2 projects - mod-host and Carla - have been using it for a few years, so it works pretty well.

**Comment by benswift** [comment]
Yeah, if you had the time & headspace that might be nice. No rush, though - at least not from me. Thanks for all your hard OSS work 🙂

**Comment by falkTX** [comment]
no worries, I will add it to my backlog :)

**Comment by yaxu** [comment]
@falkTX That would be awesome. I've been trying to get bindings working with Haskell for [TidalCycles](https://tidalcycles.org) but I'm hitting some problems. I'll have a proper look today.

**Comment by falkTX** [comment]
I can give some initial pointers.
The starting file is https://github.com/falkTX/Hylia/blob/master/hylia.h

You can look at this file https://github.com/moddevices/mod-host/blob/master/src/effects.c#L732 for an example implementation.
The hylia bits are surrounded by a `HAVE_HYLIA` macro, so they are easy to spot.

Documentation to come later. Or better, PRs welcome :)

**Comment by yaxu** [comment]
Thanks @falkTX, I'm making some progress here https://github.com/yaxu/hylia-haskell/

**Comment by fgo-ableton** [comment]
I just pushed a C wrapper for the Link API to master.
