### ISSUE TITLE
Why does LINKHUT_AUDIO_PLATFORM_DUMMY not support start-stop-sync and tempo editing?

### ISSUE THREAD

**Issue by ParticlePeter** [Ableton/link#75]
Hi, I compiled and run LINKHUT_AUDIO_PLATFORM_ASIO and LINKHUT_AUDIO_PLATFORM_DUMMY. As mentioned in the topic, start-stop-sync and tempo editing (LinkHut app reacts when changing tempo from my DAW, but not vice versa) does not work work with PLATFORM_DUMMY but does work with PLATFORM_ASIO.
As an ASIO noob that made me think that those features might depend on ASIO, which actually would not make sense.
Back to my question, is there a problem without audio engine to get those features running properly?

**Comment by fgo-ableton** [comment]
Apparently I forgot to update it 🤷 
Actually, I was about to remove the Qt apps, as mainlining them for the compilers we support on CI became a little cumbersome. The LinkHut CLI app has all the functionality the GUI apps have as well.
So I have have question: What is the scenario you want to use the dummy app for? Maybe I could add a silent CLI app, that when removing Qt.

**Comment by ParticlePeter** [comment]
Oh, as far as I understood, that is what the DUMMY CLI variant is supposed to do and does already, partially, isn't it?

> What is the scenario you want to use the dummy app for?

I am working on (non-professional) Unreal Engine 4 Support, via their plugin mechanism.

**Comment by fgo-ableton** [comment]
In general Link does not depend on an an active audio engine. `QLinkHutSilent` silent has not been updated, that's why it is currently not functioning.
To test the implementation in the Unreal Engine you should be able to use the CLI client `LinkHut'. It has the same features as `QLinkHut`.

**Comment by ParticlePeter** [comment]
I have the feeling that we are not on the same page, I'll put some things straight.
1. I am exclusively using LinkHut for my experiments.
2. I did NOT try QLinkHut as I don't (want to) have the Qt Library.
3. The CMake generated LinkHut (VS2017) project defines LINKHUT_AUDIO_PLATFORM_ASIO in its project settings, based on which specific Asio related files are included (AudioPlatform.hpp).
4. I changed that define into LINKHUT_AUDIO_PLATFORM_DUMMY and get a partially working console app without any sound rendering (as expected) but also, with the little issues I mentioned in my original post.

I got a very quick, dirty and buggy variant running in Unreal using the LinkHut example with AUDIO_PLATFORM_ASIO. Now my next step is to get rid of Asio and focus solely on Link.

I dove deeper into the code. Attention! Rubber ducking ahead!
In the case of LINKHUT_AUDIO_PLATFORM_ASIO, the start-stop-sync functionality is implemented in AudioEngine::audioCallback which in turn is being called from AudioPlatform::audioCallback (in this case defined in AudioPlatform_Asio.hpp) in turn being called from bufferSwitchTimeInfo. On the other hand, the AudioPlatform_Dummy.hpp doesn't neither need nor define an audioCallback, so the link start-stop-sync as well as tempo edit stuff is not implemented and must be handled somewhere else. 

Ok, why am I talking about this. As you can see Asio sound rendering and link start-stop-sync functionality is kind of tangled in the LINKHUT_AUDIO_PLATFORM_ASIO example (observation based on used names, e.g. AudioEngine/Platform, audioCallback, bufferSwitchTimeInfo, etc.). From a sound engineers point this approach makes probably lot of sense, but for me it's a little bit challenging to read and separate the Link from the Asio functionality (don't require the latter at all).

So, yeah, a fully working LinkHut example using LINKHUT_AUDIO_PLATFORM_DUMMY would be very helpful, for me at least.

**Comment by fgo-ableton** [comment]
Thanks for the explanation! I got it now.
I'll add a CLI app with a working DUMMY_PLATFORM.

Until then, you can maybe try something similar to what we do in `main.cpp` in LinkHut. If you haven't seen it yet, there is more documentation on https://ableton.github.io/link/.

**Comment by ParticlePeter** [comment]
First of all thanks for your help, it is highly appreciated!
I read that document already, but you made me notice the `Resource` section closer, so a win :-)
Btw, the section on `Session States and Threads` is what I meant with: `From a sound engineers point this approach makes probably lot of sense ...`

**Comment by fgo-ableton** [comment]
I just pushed some updates. There is now a `LinkHutSilent` example.

**Comment by ParticlePeter** [comment]
Thanks, all features implemented, using this as reference now! Leaving out the sound rendering makes it so much easier to follow.
