### ISSUE TITLE
Unable to export ipa file from build archive, when using LinkKit.xcframework (3.1.3)

### ISSUE THREAD

**Issue by sseyod** [Ableton/link#79]
Hi! I'm having problems exporting an ipa file from my app build archive, when using the latest LinkKit.xcframework (3.1.3)

Has anybody else had this problem?

My app works fine against actual iOS device and Simulator.
The archive build works fine.
The step to create the apk file is where it fails.

All was fine when using  LinkKit 3.0.5 ... using the fat .a library.

Thanks in advance for any suggestions.

**Comment by sseyod** [comment]
NB I tried creating my own fat binary from the different .a files in the framework folder, but this step failed.

```
lipo -create ./LinkKit.xcframework/ios-x86_64-maccatalyst/libLinkKit.a ./LinkKit.xcframework/ios-armv7_arm64/libLinkKit.a ./LinkKit.xcframework/ios-x86_64-simulator/libLinkKit.a -output fred.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: ./LinkKit.xcframework/ios-x86_64-maccatalyst/libLinkKit.a and ./LinkKit.xcframework/ios-x86_64-simulator/libLinkKit.a have the same architectures (x86_64) and can't be in the same fat output file
```

I've read that Catalyst should be x86_64h (e.g. https://onesignal.com/blog/mac-catalyst-fat-framework/) - so I wonder if you were using the correct architecture...

**Comment by fgo-ableton** [comment]
Hey,
I just tried to build an .ipa from the LinkHut example in https://github.com/Ableton/LinkKit/releases/tag/LinkKit-3.1.3.
This worked as expected. Could you check if that works for you?
[Here](https://github.com/Ableton/LinkKit/blob/6fb0bf7e9628f86ab4f533374a36b913fbb30641/makefile#L49) is where we build the xcbundle. The platform is defined as `macOS,variant=Mac Catalyst`.

**Comment by sseyod** [comment]
Hi! Many thanks for letting me know, I'll try that out - just getting a release together first.

NB I'm embedding the Link framework inside another framework, which is then bundled within the app in the normal way.

I wonder if that might be the reason for the problem?

Anyhow - I'll let you know how I get on! :)

Pete

**Comment by sseyod** [comment]
Well, that is so strange. My app is getting it's .ipa file created today from archive by Xcode. Maybe it was an Apple server-side thing gone wrong for a while?

Anyhow - thank you so much for responding. I'll close this off now. Pete
