### ISSUE TITLE
Pure ESP32 PlatformIO/Arduino lib?

### ISSUE THREAD

**Issue by DatanoiseTV** [Ableton/link#87]
It's a big pain if trying to get the ESP32 variant working on ESP32-Arduino with ASIO
and ESP-IDF includes. After including a lot of paths, I couldn't get it working.

Did someone get it to work?

**Comment by mathiasbredholt** [comment]
The main issue is the non-standard way the the Arduino library system works. As you cannot add include paths to an Arduino project, header-only libraries won't work. I've tried several times, and my conclusion is that the only way it could work would be to create a script that collects all the header files of Link and bundles them into one big header file that can be placed in the root folder of a potential Link Arduino library. Then it can simply be included in the top of an .ino file.

**Comment by DatanoiseTV** [comment]
@mathiasbredholt maybe this is worth a look? https://github.com/JamesBoer/Heady

**Comment by mathiasbredholt** [comment]
@DatanoiseTV looks perfect, I'll give it a go :)

**Comment by kokospalme** [comment]
Hello, did anybody made some futher steps in this direction so far?

**Comment by mathiasbredholt** [comment]
@kokospalme check my comment here 
https://github.com/Ableton/link/pull/68#issuecomment-1752451401
