### ISSUE TITLE
ESP32 platform not seeing peers in SoftAP mode

### ISSUE THREAD

**Issue by DatanoiseTV** [Ableton/link#88]
If I start a SoftAP on the ESP32, I can see that link is running, but it doesn't find other peers (Traktor and Ableton in this case)
```
I (99291) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.4.2
| peers: 0 | tempo: 120 | beats: 182.459766 |
| peers: 0 | tempo: 120 | beats: 184.059158 |
| peers: 0 | tempo: 120 | beats: 185.659006 |
| peers: 0 | tempo: 120 | beats: 187.259006 |
| peers: 0 | tempo: 120 | beats: 188.859158 |
| peers: 0 | tempo: 120 | beats: 190.459168 |

```

My code: https://gist.github.com/DatanoiseTV/b47fa4cb3bf96c3aefbc49176c1d22be

**Comment by vizzie** [comment]
I am seeing this, too. I have a simple fix on a branch that is working for my project. @mathiasbredholt Do you support Link over SoftAP mode on your T-1 sequencer? The ESP32 platform also is using a deprecated TCP/IP library. I'd like to port this to the esp_netif.h library while I'm at it.

**Comment by vizzie** [comment]
Whoops, @mathiasbredholt I didn't notice your pull request for this exact fix. I would definitely like this fix in place for my projects.

**Comment by fgo-ableton** [comment]
> Whoops, @mathiasbredholt I didn't notice your pull request for this exact fix. I would definitely like this fix in place for my projects.

Well, the [PR](https://github.com/Ableton/link/pulls)-description does not really make it obvious. 😄 

@mathiasbredholt If you clean that up, I could merge.

**Comment by mathiasbredholt** [comment]
@vizzie @fgo-ableton Ah yes, I agree, that wasn't clear from the description, but yes the pull request should solve the issue by adding all available interfaces (including ethernet for ethernet-enabled ESPs)

I'll take a look at it later today.

**Comment by mathiasbredholt** [comment]
@fgo-ableton @vizzie @DatanoiseTV I've updated the pull request #73, it should work with SoftAP once it's merged. This update requires ESP-IDF v4.1.

**Comment by fgo-ableton** [comment]
I merged the PR. So the issue should be solved.
