### ISSUE TITLE
Cocoapod or SPM support

### ISSUE THREAD

**Issue by cerupcat** [Ableton/link#90]
Are there any plans for adding cocoapods or Swift Package Manager support? It would help to maintain up-to-date versioning.

**Comment by fgo-ableton** [comment]
That's currently not planned. I'm not sure this would even work with the build process and licensing requirements.

**Comment by cerupcat** [comment]
For SPM, I believe you can point to xcframeworks to include. So it doesn't need to build from code. https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

In terms of licensing requirements, I'm not sure specifically to what is referred to.

**Comment by cerupcat** [comment]
Closing since I meant to post in the iOS repo. https://github.com/Ableton/LinkKit/issues/59
