### ISSUE TITLE
Access debug logs

### ISSUE THREAD

**Issue by bootsie123** [Ableton/link#96]
Hi! I noticed there is a log class utilized by many of the different files. I'm rather new to C++ and was wondering if there was a way I could tap into this data stream and print it to the console. Thanks!

**Comment by fgo-ableton** [comment]
You can enable logging by changing the log being injected in https://github.com/Ableton/link/blob/master/include/ableton/platforms/Config.hpp to `StdLog`. However, this is meant to be used when working on the Link code itself. It won't be of much use when working code using the Link library.

**Comment by bootsie123** [comment]
Gotcha. Thanks!
